### ISSUE TITLE
Have an option for a second blob container

### ISSUE THREAD

**Issue by jfix** [buzzatwork/azure-dearchiver#4]
At the moment, we have one hard-coded blob container (in the `_env` file). We need to allow access to others, and it should be as easy as possible for the user.

* Add a radio button group with two choices.
* Then, compute the blob container to use based on the supplied code (hint: we need the year).

**Comment by buzzatwork** [comment]
Done.
Add 2 buttons to manage POD or PREPRESS files (the code is used 'as is' for POD and 'substringed' for the PREPRESS).
Hope good feedback from the users.
